remote_theme: mmistakes/so-simple-theme
title: Angeliki Nikologianni
description: Architecture Portfolio
url: "https://angeliki-n.github.io" # use your actual GitHub Pages URL
baseurl: "" # leave empty unless your site is in a subfolder

plugins:
  - jekyll-remote-theme
